<!--========== BEGIN #MAIN-SECTION ==========-->
<section id="main-section">
    <!-- ========== BEGIN PARALLAX ========== -->
    <div id="parallax-section">
        <div class="image1 img-overlay1">
            <div class="container">
                <div class="caption text-center">
                    <div class="color-white text-center weight-300 medium-caption">Obten las ultimas noticias acerca</div>
                    <div class="color-white text-center weight-800 large-caption">De lo que sucede al rededor del mundo las 24H del día</div>
                </div>
            </div>
        </div>
    </div>
    <!-- ========== END PARALLAX ========== -->
    <!--========== BEGIN .MODULE ==========-->
    <section class="module">
        <!--========== BEGIN .CONTAINER ==========-->
        <div class="container">
            <!--========== BEGIN .BREAKING-NEWS ==========-->
            <!-- Begin .outer -->
            <div class="outer">
                <div class="breaking-ribbon">
                    <h4>Ultimas noticias</h4>
                </div>
                <!-- Begin .newsticker -->
                <div class="newsticker">
                    <ul>
                        <li>
                            <h4><span class="category">News:</span><a href="#"> Extra! Extra! Rethinking the 24 h News Breaking News Experience.</a></h4>
                        </li>
                        <li>
                            <h4><span class="category">Travel:</span><a href="#"> Man seriously hurt after jumping from upper level terminal while fleeing police.</a></h4>
                        </li>
                        <li>
                            <h4><span class="category">Politics:</span><a href="#"> We see momentous or informative events that are relevant to a wide audience.</a></h4>
                        </li>
                        <li>
                            <h4><span class="category">Health:</span><a href="#"> Evanston doctor gives up license after cancer drug probe.</a></h4>
                        </li>
                        <li>
                            <h4><span class="category">World:</span><a href="#"> North Coast fest organizers plan to decrease noise, increase security.</a></h4>
                        </li>
                        <li>
                            <h4><span class="category">Finance:</span><a href="#"> Credit rating hit, another big tax hike possible as clock ticks on pension overhaul.</a></h4>
                        </li>
                    </ul>
                    <div class="navi">
                        <button class="up">
                            <i class="fa fa-caret-left"></i>
                        </button>
                        <button class="down">
                            <i class="fa fa-caret-right"></i>
                        </button>
                    </div>
                </div>
                <!-- End .newsticker -->
            </div>
            <!-- End .outer -->
            <!--========== END .BREAKING-NEWS ==========-->
            <!--========== BEGIN #NEWS-SLIDER ==========-->
            <div id="news-slider" class="owl-carousel">
                <div class="news-slide">
                   <?php for($i=0;$i<4;$i++) { $aleatorio=rand(0,14);?>
                    <div class="news-slider-layer <?=$clases[$i]?>">
                        <?php $subcategoria = \Modules\Models\CdSubcategory::findFirst("subid=".$noticias[$aleatorio]['subid']); ?>
                        <a href="/ver-noticias/<?=$subcategoria->getPermalink()?>/<?=$noticias[$aleatorio]['permalink']?>" target="_blank">
                            <div class="content">
                                <span class="category-tag bg-1"><?=$subcategoria->getName()?></span>
                                <p><?=$noticias[$aleatorio]['title']?></p>
                            </div>
                            <img src="/dash/src/<?=$noticias[$aleatorio]['images']?>" alt="">
                        </a>
                    </div>
                    <?php }?>
                </div>
                <div class="news-slide">
                    <?php for($i=0;$i<4;$i++) { $aleatorio=rand(0,14);?>
                        <div class="news-slider-layer <?=$clases[$i]?>">
                            <?php $subcategoria = \Modules\Models\CdSubcategory::findFirst("subid=".$noticias[$aleatorio]['subid']); ?>
                            <a href="/ver-noticias/<?=$subcategoria->getPermalink()?>/<?=$noticias[$aleatorio]['permalink']?>" target="_blank">
                                <div class="content">
                                    <span class="category-tag bg-1"><?=$subcategoria->getName()?></span>
                                    <p><?=$noticias[$aleatorio]['title']?></p>
                                </div>
                                <img src="/dash/src/<?=$noticias[$aleatorio]['images']?>" alt="">
                            </a>
                        </div>
                    <?php }?>
                </div>
                <div class="news-slide">
                    <?php for($i=0;$i<4;$i++) { $aleatorio=rand(0,14);?>
                        <div class="news-slider-layer <?=$clases[$i]?>">
                            <?php $subcategoria = \Modules\Models\CdSubcategory::findFirst("subid=".$noticias[$aleatorio]['subid']); ?>
                            <a href="/ver-noticias/<?=$subcategoria->getPermalink()?>/<?=$noticias[$aleatorio]['permalink']?>" target="_blank">
                                <div class="content">
                                    <span class="category-tag bg-1"><?=$subcategoria->getName()?></span>
                                    <p><?=$noticias[$aleatorio]['title']?></p>
                                </div>
                                <img src="/dash/src/<?=$noticias[$aleatorio]['images']?>" alt="">
                            </a>
                        </div>
                    <?php }?>
                </div>
            </div>
            <!--========== END .NEWS-SLIDER ==========-->
        </div>
    </section>
    <!--========== END .MODULE ==========-->
    <!--========== BEGIN .MODULE ==========-->
    <section class="module highlight" wp-site-content wp-body-class wp-site-name wp-title wp-site-desc wp-header-image>
        <div class="container">
            <div class="module-title">
                <h3 class="title"><span class="bg-1">Internacionales</span></h3>
                <h3 class="subtitle">Noticias  Destacadas</h3>
            </div>
            <!--========== BEGIN .ROW ==========-->
            <div class="row no-gutter">
                <!--========== BEGIN .COL-MD-6 ==========-->
                <div class="col-sm-6 col-md-6">
                    <!--========== BEGIN .NEWS ==========-->
                    <div class="news">
                        <!-- Begin .item -->
                        <div class="item">
                            <div class="item-image-1">
                                <a class="img-link" href="#">
                                    <img class="img-responsive img-full" src="/dash/src/<?=$internacionalesDestacadas[0]['images']?>" alt="">
                                </a>
                            </div>
                            <div class="item-content">
                                <div class="title-left title-style04 underline04">
                                    <h3><a href="#"><?=$internacionalesDestacadas[0]['title']?></a></h3>
                                </div>
                                <p><a href="#" target="_blank" class="tamanioLetra"><?=$internacionalesDestacadas[0]['description']?></a></p>
                                <div>
                                    <a href="news.html" target="_blank"><span class="read-more">News</span></a>
                                </div>
                            </div>
                        </div>
                        <!-- End .item -->
                        <!-- Begin .item -->
                        <div class="item">
                            <div class="item-image-1">
                                <a class="img-link" href="#">
                                    <img class="img-responsive img-full" src="dash/src/<?=$internacionalesDestacadas[1]['images']?>" alt="">
                                </a>
                            </div>
                            <div class="item-content">
                                <div class="title-left title-style04 underline04">
                                    <h3><a href="#"><?=$internacionalesDestacadas[1]['title']?></h3>
                                </div>
                                <p><a href="#" target="_blank" class="tamanioLetra"><?=$internacionalesDestacadas[1]['description']?></a></p>
                            </div>
                        </div>
                        <!-- End .item -->
                    </div>
                    <!--========== END .NEWS ==========-->
                </div>
                <!--========== END .COL-MD-6 ==========-->
                <!--========== BEGIN .COL-MD-6 ==========-->
                <div class="col-sm-6 col-md-6">
                    <!--========== BEGIN .NEWS==========-->
                    <div class="news">
                        <!-- Begin .item-->
                        <div class="item">
                            <div class="item-image-1">
                                <a class="img-link" href="#">
                                    <img class="img-responsive img-full" src="/dash/src/<?=$internacionalesDestacadas[2]['images']?>" alt="">
                                </a>
                            </div>
                            <div class="item-content">
                                <div class="title-left title-style04 underline04">
                                    <h3><a href="#"><?=$internacionalesDestacadas[2]['title']?></a></h3>
                                </div>
                                <p><a href="#" target="_blank" class="tamanioLetra"><?=$internacionalesDestacadas[2]['description']?></a></p>
                            </div>
                        </div>
                        <!-- End .item-->
                        <!-- Begin .item -->
                        <div class="item">
                            <div class="item-image-1">
                                <a class="img-link" href="#">
                                    <img class="img-responsive img-full" src="/dash/src/<?=$internacionalesDestacadas[3]['images']?>" alt="">
                                </a>
                            </div>
                            <div class="item-content">
                                <div class="title-left title-style04 underline04">
                                    <h3><a href="#"><?=$internacionalesDestacadas[3]['title']?></a></h3>
                                </div>
                                <p><a href="#" target="_blank" class="tamanioLetra"><?=$internacionalesDestacadas[3]['description']?></a></p>

                        </div>
                        <!-- End .item -->
                    </div>
                    <!--========== END .NEWS ==========-->
                </div>
                <!--========== END .COL-MD-6 ==========-->
            </div>
        </div>
    </section>
    <!--========== END .MODULE ==========-->
    <!--========== BEGIN .MODULE ==========-->
    <section class="module">
        <div class="container">
            <div class="row no-gutter">
                <!--========== BEGIN .COL-MD-8 ==========-->
                <div class="col-md-8">
                    <!--========== BEGIN .NEWS ==========-->
                    <div class="news">
                        <div class="module-title">
                            <h3 class="title"><span class="bg-11">Nacionales</span></h3>
                            <h3 class="subtitle">Destacados</h3>
                        </div>
                        <!-- Begin .item-->
                        <?php for($i=0;$i<4;$i++){?>
                        <div class="item">
                            <div class="item-image-2">
                                <a class="img-link" href="#">
                                    <img class="img-responsive img-full" src="/dash/src/<?=$destNationalArray[$i]['images']?>" alt="">
                                </a>
                            </div>
                            <div class="item-content">
                                <div class="title-left title-style04 underline04">
                                    <h3><a href="#"><strong><?=$destNationalArray[$i]['title']?></h3>
                                </div>
                                <p><a href="#"> <?=$destNationalArray[$i]['description']?></a></p>
                            </div>
                        </div>
                        <?php } ?>
                        <!-- End .item-->
                    </div>
                    <!--========== End .NEWS ==========-->
                </div>
                <!--========== End .COL-MD-8 ==========-->
                <!--========== BEGIN .COL-MD-4 ==========-->
                <div class="col-md-4">
                    <!-- Begin .sidebar-add-place -->
                    <div class="sidebar-add-place">
                        <a href="https://themeforest.net/item/24h-news-broadcast-news-tv-channel-news-magazine-template/18614179" target="_blank">
                            <img src="img/banner_400x270.jpg" alt="">
                        </a>
                    </div>
                    <!-- End .sidebar-add-place -->
                    <!-- Begin .block-title-1 -->
                    <div class="block-title-1">
                        <h3>Recopilacion de las ultimas 24H</h3>
                    </div>
                    <!-- End .block-title-1 -->
                    <!--========== BEGIN .SIDEBAR-NEWSFEED ==========-->
                    <div class="sidebar-newsfeed">
                        <!-- Begin .newsfeed -->
                        <div class="newsfeed-3">
                            <ul>
                                <?php foreach ($feed as $i=>$key): ?>
                                <li>
                                    <div class="item">
                                        <div class="item-image">
                                            <a class="img-link" href="#">
                                                <img class="img-responsive img-full" src="/dash/src/<?=$key['images']?>" alt="">
                                            </a>
                                        </div>
                                        <div class="item-content">
                                            <h4 class="ellipsis"><a href="#"><?=$key['title']?></a></h4>
                                        </div>
                                    </div>
                                </li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                        <!-- End .newsfeed -->
                    </div>
                    <!--========== END .SIDEBAR-NEWSFEED ==========-->
                </div>
                <!--========== END .COL-MD-4 ==========-->
            </div>
        </div>
    </section>
    <!--========== END .MODULE ==========-->
    <!--========== BEGIN .MODULE ==========-->
    <section class="module dark">
        <div class="container">
            <div class="show-info">
                <h4 class="schedule-logo bg-1"><a href="" target="_blank">Entretenimiento</a></h4>
                <div class="show-title">
                    <h2><?=$newsEntretaiment[0]['title']?></h2>
                    <h3><?=$newsEntretaiment[0]['author']?></h3>
                </div>
                <h4><a class="show-info-button bg-1" href="#">Noticia de entretenimiento más destacada</a></h4>

            </div>
            <div class="schedule-squares">
                <span class="square2"></span>
                <span class="square3"></span>
                <span class="square4"></span>
                <span class="square5"></span>
                <span class="square6"></span>
                <span class="square7"></span>
                <span class="square8"></span>
                <span class="square9"></span>
                <span class="square10"></span>
                <span class="square11"></span>
            </div>
        </div>
    </section>
    <!--========== END .MODULE ==========-->
    <!--========== BEGIN .MODULE ==========-->
    <section class="module highlight">
        <div class="container">
            <div class="row no-gutter">
                <!--========== BEGIN .COL-MD-8 ==========-->
                <div class="col-md-8">
                    <div class="module-title">
                        <h3 class="title"><span class="bg-1">Politica</span></h3>
                        <h3 class="subtitle">Noticias destacadas</h3>
                    </div>
                    <!--========== BEGIN .ROW ==========-->
                    <div class="row no-gutter">
                        <!--========== BEGIN .COL-MD-3 ==========-->
                        <div class="col-xs-12 col-sm-3 col-md-3">

                            <!-- End .list list-mark-1 -->
                        </div>
                        <!--========== END .COL-MD-3 ==========-->
                        <!--========== BEGIN .COL-MD-9 ==========-->
                        <div class="col-xs-12 col-sm-9 col-md-9">
                            <!--========== BEGIN .NEWS ==========-->
                            <div class="news">
                                <?php for($i=0;$i<4;$i++){ ?>
                                <div class="item">
                                    <div class="item-image-3">
                                        <a class="img-link" href="#">
                                            <img class="img-responsive img-full" src="/dash/src/<?=$arraPolitic[$i]['images']?>" alt="">
                                        </a>
                                    </div>
                                    <div class="item-content">
                                        <div class="title-left title-style04 underline04">
                                            <h3><a href="#"><?=$arraPolitic[$i]['title']?></a></h3>
                                        </div>
                                        <div class="scroll_barNews">
                                            <p><a href="#" target="_blank" ><?=$arraPolitic[$i]['description']?></a></p>
                                        </div>
                                    </div>
                                </div>
                                <?php } ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--========== END .MODULE ==========-->
