<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <form id="formLeft" class="navbar-form navbar-center">
            <button class="socialNeworks">
                <a class="fa fa-twitter" aria-hidden="true" id="twitter" ></a>
            </button>
            <button class="socialNeworks">
            <a class="fa fa-facebook-square"aria-hidden="true"></a>
            </button>
            <button class="socialNeworks">
                <a class="fa fa-youtube-play" aria-hidden="true" id="youtube"></a>
            </button>
        </form>
     <form id="formCenter" class="navbar-form navbar-center">
        <div class="navbar-header">
            <a class="navbar-brand" style="font-size: 30px;">Central de noticias</a>
        </div>
      </form>
        <div id="navbar" class="navbar-collapse collapse">
            <form id="formRight" class="navbar-form navbar-right">
                <button type="button" id="bIniciarSesion" class="btn btn-success">Iniciar sesion</button>
            </form>
        </div><!--/.navbar-collapse -->
    </div>
</nav>
</br>
</br>
</br>
</br>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>
                <li><a href="#">Reports</a></li>
                <li><a href="#">Analytics</a></li>
                <li><a href="#">Export</a></li>
            </ul>
            <ul class="nav nav-sidebar">
                <li><a href="">Nav item</a></li>
                <li><a href="">Nav item again</a></li>
                <li><a href="">One more nav</a></li>
                <li><a href="">Another nav item</a></li>
                <li><a href="">More navigation</a></li>
            </ul>
            <ul class="nav nav-sidebar">
                <li><a href="">Nav item again</a></li>
                <li><a href="">One more nav</a></li>
                <li><a href="">Another nav item</a></li>
            </ul>
        </div>
<footer>

</footer>