<div class="container">
<div class="row">
    <div class="col-md-12" style="text-align: center;" >
        <h1><?=$new->getTitle()?></h1>
    </div>
</div>
<?php if($new->getSubtitle()!=null){ ?>
<br>
<div class="row">
    <div class="col-md-12" style="text-align: center;" >
        <h2><?=$new->getSubtitle()?></h2>
    </div>
</div>
<?php }?>
    <br>
<div class="row">
    <div class="col-md-12" style="text-align: center;" >
       <h3><?=$new->getDescription()?></h3>
    </div>
</div>
<br>
<div class="row">
  <div class="col-md-12" style="text-align: center;" >
        <img src="/dash/src/<?=$new->getImages()?>">
  </div>
</div>
<br>
<div class="row">
    <div class="col-md-12" style="text-align: left;" >
       <h6>Calificacion: <span id="starts"></span></h6>
    </div>
</div>
<br>
<div class="row">
    <div class="col-md-12" style="text-align: center;" >
       <p><?=$new->getContent()?></p>
    </div>
</div>
    <?php if($galeria->toArray()!=null){ ?>
    <br>
    <div class="row">
        <div class="col-md-12" style="text-align: right" >
            <div id="carouselRapido" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner" role="listbox">
                     <?php $contador=0; foreach ($galeria as $key): ?>
                     <?php if($contador>0){
                      ?>
                        <div class="item"><img style="width: 100%;height: 30pc;" src="/dash/src/<?=$key->getImg()?>" alt="banner1"></div>
                    <?php }else{ ?>
                    <div class="item active"><img style="width: 100%;height: 30pc;" src="/dash/src/<?=$key->getImg()?>" alt="banner1"></div>
                    <?php $contador++; } ?>

                    <?php endforeach; ?>
                </div>
                <a class="left carousel-control" href="#carouselRapido" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#carouselRapido" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

        </div>
    </div>
    <?php } ?>

<br>
<div class="row">
    <div class="col-md-12" style="text-align: right" >
        <p>Escrito por: <strong><?=$new->getAuthor()?></strong></p>
    </div>
</div>

</div>