<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="<?=$this->url->get('front/css/myStyle.css')?>">
    <link rel="stylesheet" type="text/css" href="<?=$this->url->get('front/css/bootstrap.min.css')?>">
    <link rel="stylesheet" type="text/css" href="<?=$this->url->get('front/css/font-awesome.css')?>">


    <title>Central de noticias</title>
  </head>
  <body>
        <?= $this->getContent() ?>
        <script src="<?=$this->url->get('front/js/jquery.min.js')?>"></script>
        <script src="<?=$this->url->get('front/js/popper.min.js')?>"></script>
        <script src="<?=$this->url->get('front/js/bootstrap.min.js')?>"></script>
        <script src="<?=$this->url->get('front/js/editable.js')?>"></script>
        <script src="<?=$this->url->get('front/js/myAjax.js')?>"></script>

  </body>


</html>
